// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANCJixSe64wz3FHK8mlaDu9UFMnMrdSZo',
    appId: '1:191097124850:android:395334bbebc013c10f9d6b',
    messagingSenderId: '191097124850',
    projectId: 'kissanfresh-a72c1',
    storageBucket: 'kissanfresh-a72c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPp4uR7GG4zNmE3bQjZSTzwfOHHeo-yF0',
    appId: '1:191097124850:ios:4a0a8c2d58b3b1440f9d6b',
    messagingSenderId: '191097124850',
    projectId: 'kissanfresh-a72c1',
    storageBucket: 'kissanfresh-a72c1.firebasestorage.app',
    androidClientId: '191097124850-gofonjgu1lad5cfbvdekav69havj82n4.apps.googleusercontent.com',
    iosClientId: '191097124850-1t40h931es62l3fut64aund0427k0e3h.apps.googleusercontent.com',
    iosBundleId: 'com.kissanfresh.app',
  );
}
